services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: stalker_kombat
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d stalker_kombat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app_net

  #  redis:
  #    image: redis:7-alpine
  #    container_name: redis
  #    ports:
  #      - "6379:6379"
  #    command: redis-server --save 60 1 --loglevel warning
  #    healthcheck:
  #      test: [ "CMD", "redis-cli", "ping" ]
  #      interval: 10s
  #      timeout: 3s
  #      retries: 3
  #      start_period: 10s

  #  kafka:
  #    image: confluentinc/cp-kafka:7.4.0
  #    container_name: kafka
  #    depends_on:
  #      - zookeeper
  #    ports:
  #      - "9092:9092"
  #    environment:
  #      KAFKA_BROKER_ID: 1
  #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  gateway:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
    networks:
      - app_net

  auth:
    build:
      context: services
      dockerfile:  auth/Dockerfile
    container_name: auth
    env_file: .env
    volumes:
      - ./services/auth:/app
      - ./versions:/app/migrations/versions
      - ./services/utils:/utils
    depends_on:
      #      redis:
      #        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - app_net

  inventory:
    build:
      context: services
      dockerfile:  inventory/Dockerfile
    container_name: inventory
    env_file: .env
    volumes:
      - ./services/inventory:/app
      - ./versions:/app/migrations/versions
      #- ./services/utils:/app/utils
    depends_on:
      #      redis:
      #        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data: